[package]
name = "rust-cli-magic-8-ball"
version = "0.1.0"
authors = ["Jesper Kallunki <jesper.kallunki@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rand = "0.7.3"
